Output vhs/a7-getting-started.gif

Set WindowBar Colorful
Set FontSize 18
Set Width 1200
Set Height 720
Set TypingSpeed 125ms

Type@95ms "So, you saw the first video?"
Sleep 2s
Backspace 28
Sleep 3s

Type@95ms "Are you sitting comfortably?"
Sleep 2s
Backspace 30
Sleep 3s

Type@95ms "Then let us create a Journal entry!"
Sleep 2s
Backspace 36
Sleep 3s

Type@95ms "Remember, press 'n' to create a new entry."
Sleep 2s
Backspace 42
Sleep 3s

Type "a7"
Sleep 1s
Enter

Sleep 2s
Type "n"
Sleep 3s

Type@85ms "What A Day!"
Sleep 2s
Tab
Sleep 3s
Type@200ms "It wasn't a typical thursday."
Enter
Enter
Type@200ms "It is as it ever was."
Enter
Enter
Type@200ms "Wednesday..."
Sleep 2s

Ctrl+S
Sleep 3s
